# Generated by Django 5.0.3 on 2024-11-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
